Providers optional TOFU auth wire clients, ephemeral clients gc
katzenpost/server pull request #151
Opened 2021-08-21 05:04 UTC by david415

Here we add two Provider configuration parameters:
1. turn on TOFU authentication
2. ephemeral client accounts

2021-08-22 14:48 UTC, mixmasala reviewed
see the comments around the returned flag isValid and the timestamp logging portions, otherwise I think this looks good

2021-08-22 14:48 UTC, mixmasala commented on spool/boltspool/boltspool.go
> +	receivedTimeKey = "receivedTime"
the server should not store message received timestamps

2021-08-22 14:48 UTC, mixmasala commented on spool/boltspool/boltspool.go
> +
why store the received time?

2021-08-22 14:48 UTC, mixmasala commented on userdb/boltuserdb/boltuserdb.go
> +		} else {
should isValid = true now?

2021-08-22 14:48 UTC, mixmasala commented on userdb/boltuserdb/boltuserdb.go
> +		}
or should isValid = true now?

2021-08-28 09:57 UTC, david415 commented
It works. I tested it locally with a docker nonvoting mixnet. I used my ping command to test.

2021-08-31 13:01 UTC, mixmasala requested changes
looks good but I am confused how the changes to the tests demonstrate the new feature works.

2021-09-04 00:55 UTC, david415 commented on spool/boltspool/boltspool.go
> +	receivedTimeKey = "receivedTime"
resolved

2021-09-04 00:55 UTC, david415 commented on userdb/boltuserdb/boltuserdb.go
> +		} else {
resolved

2021-09-04 00:57 UTC, david415 commented
One thing this PR needs is a docker integration test:
1. the client generates new keys and connects to the provider and then disconnects.
2. the client reconnects with the same key
3. the client claims to be the same identity as the previous key but in fact uses a different key, authentication should fail

2021-09-04 01:16 UTC, david415 commented on internal/provider/provider.go
> +		if pkt == nil {
Yes I think you're right. The above switch statement needs to have a continue or return in each case but that new GC case I added doesn't have a continue so that causes pkt to be nil ;-( so that's bad. but good catch!

2021-09-04 01:18 UTC, david415 commented on internal/provider/provider.go
> +		if pkt == nil {
resolved

2021-09-04 01:32 UTC, david415 commented on internal/incoming/listener.go
> +// GetConnIdentities returns a slice of byte slices each corresponding
Yes, I see what you are saying. The call site where this is used is concerned with AdditionalData but not PublicKey.

I'm not sure. It could go either way. Certainly more expressive types are more expressive. Clear code is clear. The intention of the function signature can also be made clear with a API comment. We should be using proper golang API comments anyway. So, I will think about this.

Here's the actual call site to consider:

```
func (s *boltSpool) VacuumExpired(udb userdb.UserDB, ignoreIdentities [][]byte) error {
	ignoreMap := make(map[[sConstants.RecipientIDLength]byte]interface{})
	for _, ignore := range ignoreIdentities {
		key := [sConstants.RecipientIDLength]byte{}
		copy(key[:], ignore)
		ignoreMap[key] = struct{}{}
	}
	return s.db.Update(func(tx *bolt.Tx) error {
		uBkt := tx.Bucket([]byte(usersBucket))
		usersCursor := uBkt.Cursor()
		for identity, _ := usersCursor.First(); identity != nil; identity, _ = usersCursor.Next() {
			key := [sConstants.RecipientIDLength]byte{}
			copy(key[:], identity)
			if _, ok := ignoreMap[key]; ok {
				continue
			}
			_ = udb.Remove(identity)
			_ = uBkt.DeleteBucket(identity)
		}
		return nil
	})
}
```

2021-09-04 01:34 UTC, david415 commented on internal/incoming/listener.go
> +// GetConnIdentities returns a slice of byte slices each corresponding
Oh I see you've snuck in another quip: Yes the AdditionalData could have anything... and our wire auth for the server treat this whatever 32 byte value.... in a very specific way... as you can see, it's a key into the boltdb bucket. It need not be the link pub key. It's an account "identity".

2021-09-04 01:36 UTC, david415 commented on internal/incoming/listener.go
> +// GetConnIdentities returns a slice of byte slices each corresponding
mailproxy was using it as the "username"... aka recipient identity string. But... it was still a unique 32 byte value. Thus, for the purposes of this particular PR it suffices as a way to uniquely address a specific user.... as in the case of the GC code mentioned.

2021-09-04 01:44 UTC, david415 commented on userdb/boltuserdb/boltuserdb_test.go
> +	assert.True(d.IsValid([]byte("malory"), testUsers["alice"]), "IsValid('malory', k)")
This test must have it's assertion inverted because our TOFU authentication require "IsValid" to return true for all cases except for the case where a new key is used with an existing identity which is linked with a different key. Make sense?

2021-09-04 01:44 UTC, david415 commented on userdb/boltuserdb/boltuserdb_test.go
> +	assert.True(d.IsValid([]byte("malory"), testUsers["alice"]), "IsValid('malory', k)")
Same reason as above.

2021-09-04 02:11 UTC, david415 commented
DO NOT MERGE. or at least not yet. There's a bug and I wrote a test that shows the bug but have not yet fixed it.

2021-09-04 03:44 UTC, david415 commented
I believe I have fixed the problem with the tests... and in the process of doing so I discovered another bug in IsValid... which I have now fixed.

2021-09-04 03:45 UTC, david415 commented
> looks good but I am confused how the changes to the tests demonstrate the new feature works.

It should now be more clear what the tests are doing and why. I've created two new TOFU tests and left the old tests the way they were before.

2021-09-06 17:46 UTC, leif commented
This PR has been migrated to https://github.com/katzenpost/katzenpost/pull/5.

2021-09-06 17:46 UTC, closed without merging